version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL
    versions:
    - 5.0.2
    - 5.0.5
  - dependency-name: Swashbuckle.AspNetCore.Swagger
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Swashbuckle.AspNetCore.SwaggerUI
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: MongoDB.Driver.Core
    versions:
    - 2.11.6
    - 2.12.0
    - 2.12.1
    - 2.12.2
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
  - dependency-name: Microsoft.Extensions.Logging.Debug
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.Hosting
    versions:
    - 5.0.0
